name: Nermine Hammam
favicon: null
layout_spectrum: 0.11559074837714434
typography_spectrum: 0.029631498735398054
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.03190177958458662
  lightness: 0.0005241755861788988
  saturation: 0.3627199528273195
  rhythmicContrast: 0.78178700665012
purpose: []
